### ISSUE TITLE
Error running react-native run-ios

### ISSUE THREAD

**Issue by adityakandari** [jondot/ReactNativeKatas#1]
clang: error: no such file or directory: '/Users/user/reactnative/ReactNativeKatas/node_modules/react-native-view-snapshot/ViewSnapshotter.m'
clang: error: no input files

**Comment by adityakandari** [comment]
FIxed by installing  npm i --save react-native-view-snapshot

**Comment by jondot** [comment]
Thanks, these were leftovers from the first iteration, where I did visual diffs on the native side. I've cleaned these up. I'll do some more clean up and testing today.

**Comment by adityakandari** [comment]
alright man :D
