### ISSUE TITLE
Not Being Able to Clear Second Kata

### ISSUE THREAD

**Issue by alayek** [jondot/ReactNativeKatas#11]
Hi,

I am just getting started with react-native and I found your repo from the awesome list. 🐵 

I tried the [solution](https://github.com/jondot/ReactNativeKatas/blob/master/src/katas/flex/Alignment.js) for the second [problem](https://github.com/jondot/ReactNativeKatas/blob/master/src/katas/flex/Alignment.test.js), but my second kata is not passing the tests. 😢 

<img width="1440" alt="screen shot 2016-08-07 at 6 42 18 pm" src="https://cloud.githubusercontent.com/assets/5607371/17462558/b3188f14-5cce-11e6-9237-0700d726ab53.png">

Even after hot-reloading, the error is not going away. I tried by restarting too.

---

I don't know enough React-native to decide if this is an issue or if I am doing anything wrong. Either way, thanks in advance! ✨

**Comment by jondot** [comment]
Hi @alayek is this still a problem? if so, please feel free to reopen :)
