### ISSUE TITLE
TypeError: methods.forEach is not a function

### ISSUE THREAD

**Issue by kurtzilla** [jondot/ReactNativeKatas#14]
Just trying to follow along but am stopped when running 
`
react-native run-ios
`
I receive the same error in xcode  
What am I missing?

![screen shot 2016-10-10 at 11 21 54 am](https://cloud.githubusercontent.com/assets/579932/19244910/c60f2b02-8edb-11e6-825d-9073162d990a.png)

**Comment by jondot** [comment]
I'm closing due to clean up. Please reopen if this is still a problem
