### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by ebrahim95** [jondot/ReactNativeKatas#15]
When the app is compiling it spits out this error:

![image](https://cloud.githubusercontent.com/assets/14169174/20366345/4081d532-ac10-11e6-81dd-2fbc72a2dbb8.png)

**Comment by jondot** [comment]
Sorry currently we only support iOS simulator, please see this for more information why:
https://github.com/jondot/ReactNativeKatas/issues/7

**Comment by ebrahim95** [comment]
Thanks for the information.
