### ISSUE TITLE
Quick Start: the "npm i" step

### ISSUE THREAD

**Issue by bellentuck** [jondot/ReactNativeKatas#18]
Hi,

Incredibly basic question here--an easy win for whoever can answer!

I have a working react-native setup. I've run other projects successfully via `run-ios`. I have followed the first "Quick Start" step and have cloned this repo locally. 

From my ReactNativeKatas folder, `react-native run-ios` prompts the following command line response: "Command `run-ios` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project." OK, so, on to "Quick Start" step two: `npm i`.

**Do I literally input `npm i` on the command line? Or `npm install`? Or something else? What exactly am I needing to install? And what is the literal text I input on the command line to accomplish this?**

I ran into npm troubles setting up react-native, and am trying to avoid the headache now if possible. :)

Thanks,
Ben

**Comment by jondot** [comment]
To set up the project, you type "npm i", which is a shorthand for "npm install".
This projects already assumed that you have the basic React Native toolset installed, which means you have `react-native` binary working. If you missed that part for some reason, then you can easily install it with `npm i -g react-native-cli`

Hope this helps!
