### ISSUE TITLE
Method does not override or implement a method from a supertype ?? On Android Platform

### ISSUE THREAD

**Issue by AugustoAleGonZhipCode** [jondot/ReactNativeKatas#19]
Hello, I am currently facing an error while I am trying to run on my device. I don't know exactly what to do. I really want to use this amazing project because I thing it is the right tool for learning faster and better.

I am on Windows 10. This is the error so far:

```
C:\Users\Augusto\Documents\ReactNativeKatas\android\app\src\main\java\com\reactnativekatas\MainActivity.java:27: error: method does not override or implement a method from a supertype
    @Override
    ^
C:\Users\Augusto\Documents\ReactNativeKatas\android\app\src\main\java\com\reactnativekatas\MainActivity.java:36: error: method does not override or implement a method from a supertype
    @Override
    ^
2 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

I was reading and probably it is a plugin that it is not working right. I am really a newbie on React Native.

**Comment by jondot** [comment]
Hi, 
Katas run on iOS only,  see more here: #20

**Comment by AugustoAleGonZhipCode** [comment]
Thanks jondot. I would like to implement it on Android too. I have to admit it is an amazing project for learning react-native on live coding. I want to contribute in some way. If you need a hand let me know.

**Comment by jondot** [comment]
@AugustoAleGonZhipCode thanks! 
right now my plan is:

1 - To attempt a React Native core upgrade. This can break everything but it'll be one thing. 
2 - The next thing would be to find implementations of snapshots on Android that will perform in a good way.

If (1) will not provide that much value, then I will attempt only (2). When I'll start that work I'll ping you - thanks!

**Comment by AugustoAleGonZhipCode** [comment]
@jondot Thanks to your amazing code.

It seems an awesome plan. I understand by first hand the break everything part.
Let me know if I can help in something I will start on it.
