### ISSUE TITLE
'RCTRootView.h' not found.

### ISSUE THREAD

**Issue by tahirwaseer** [jondot/ReactNativeKatas#4]
I have cloned the project on my local machine and run npm i. All went successful but when I try to build and run the project from XCode it gives this error " 'RCTRootView.h' not found." and build fails.

**Comment by jondot** [comment]
Hi Tahir,
Thanks for trying this out.
For your issue - for some reason I believe your `npm install` did not go successfully. 
Sometimes errors in npm are hard to find - are you sure it finished successfully?

**Comment by tahirwaseer** [comment]
Here is the output of npm i;
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
 
> bufferutil@1.2.1 install /Users/tahir/Developer/react-native/ReactNativeKatas/node_modules/react-native/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
 
> utf-8-validate@1.2.1 install /Users/tahir/Developer/react-native/ReactNativeKatas/node_modules/react-native/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
 
> spawn-sync@1.0.15 postinstall /Users/tahir/Developer/react-native/ReactNativeKatas/node_modules/react-native/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

|
> fsevents@1.0.12 install /Users/tahir/Developer/react-native/ReactNativeKatas/node_modules/react-native/node_modules/fbjs-scripts/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/tahir/Developer/react-native/ReactNativeKatas/node_modules/react-native/node_modules/fbjs-scripts/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" is installed via remote
fs-extra@0.30.0 node_modules/fs-extra
├── path-is-absolute@1.0.0
├── rimraf@2.5.2
├── graceful-fs@4.1.4
├── jsonfile@2.3.1
└── klaw@1.3.0

glob@7.0.5 node_modules/glob
├── path-is-absolute@1.0.0
├── fs.realpath@1.0.0
├── inherits@2.0.1
├── once@1.3.3 (wrappy@1.0.2)
├── inflight@1.0.5 (wrappy@1.0.2)
└── minimatch@3.0.2 (brace-expansion@1.1.5)

react-native-fs@1.5.1 node_modules/react-native-fs
├── utf8@2.1.1
├── base-64@0.1.0
└── bluebird@2.10.2

ramda@0.21.0 node_modules/ramda

node-resemble-js@0.0.5 node_modules/node-resemble-js
└── pngjs@2.2.0

react@15.0.2 node_modules/react
├── object-assign@4.1.0
├── loose-envify@1.2.0 (js-tokens@1.0.3)
└── fbjs@0.8.3 (immutable@3.8.1, ua-parser-js@0.7.10, promise@7.1.1, isomorphic-fetch@2.2.1, core-js@1.2.6)

react-native-vector-icons@2.0.3 node_modules/react-native-vector-icons
├── lodash@4.13.1
└── yargs@4.7.1 (decamelize@1.2.0, y18n@3.2.1, camelcase@3.0.0, set-blocking@1.0.0, window-size@0.2.0, require-main-filename@1.0.1, yargs-parser@2.4.0, lodash.assign@4.0.9, os-locale@1.4.0, string-width@1.0.1, cliui@3.2.0, pkg-conf@1.1.3, read-pkg-up@1.0.1)

react-native@0.26.3 node_modules/react-native
├── regenerator-runtime@0.9.5
├── react-clone-referenced-element@1.0.1
├── absolute-path@0.0.0
├── graceful-fs@4.1.4
├── stacktrace-parser@0.1.3
├── progress@1.1.8
├── base64-js@0.0.8
├── wordwrap@1.0.0
├── event-target-shim@1.1.1
├── react-timer-mixin@0.13.3
├── immutable@3.7.6
├── semver@5.1.0
├── image-size@0.3.5
├── bser@1.0.2 (node-int64@0.4.0)
├── opn@3.0.3 (object-assign@4.1.0)
├── debug@2.2.0 (ms@0.7.1)
├── json-stable-stringify@1.0.1 (jsonify@0.0.0)
├── temp@0.8.3 (os-tmpdir@1.0.1, rimraf@2.2.8)
├── source-map@0.4.4 (amdefine@1.0.0)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, ansi-styles@2.2.1, supports-color@2.0.0, strip-ansi@3.0.1, has-ansi@2.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── rebound@0.0.13
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── promise@7.1.1 (asap@2.0.4)
├── worker-farm@1.3.1 (xtend@4.0.1, errno@0.1.4)
├── node-haste@2.10.1 (throat@2.0.2, denodeify@1.2.1)
├── sane@1.3.4 (fb-watchman@1.9.0, watch@0.10.0, minimist@1.2.0, exec-sh@0.2.0, minimatch@0.2.14, walker@1.0.7)
├── yargs@3.32.0 (decamelize@1.2.0, camelcase@2.1.1, y18n@3.2.1, window-size@0.1.4, cliui@3.2.0, string-width@1.0.1, os-locale@1.4.0)
├── art@0.10.1
├── node-fetch@1.5.3 (is-stream@1.1.0, encoding@0.1.12)
├── ws@0.8.1 (options@0.0.6, ultron@1.0.2, bufferutil@1.2.1, utf-8-validate@1.2.1)
├── json5@0.4.0
├── uglify-js@2.6.3 (async@0.2.10, uglify-to-browserify@1.0.2, source-map@0.5.6, yargs@3.10.0)
├── connect@2.30.2 (bytes@2.1.0, cookie-signature@1.0.6, utils-merge@1.0.0, on-headers@1.0.1, content-type@1.0.2, pause@0.1.0, vhost@3.0.2, response-time@2.3.1, fresh@0.3.0, parseurl@1.3.1, cookie@0.1.3, basic-auth-connect@1.0.0, cookie-parser@1.3.5, depd@1.0.1, qs@4.0.0, method-override@2.3.6, connect-timeout@1.6.2, serve-favicon@2.3.0, http-errors@1.3.1, morgan@1.6.1, express-session@1.11.3, finalhandler@0.4.0, type-is@1.6.13, multiparty@3.3.2, serve-static@1.10.3, csurf@1.8.3, compression@1.5.2, errorhandler@1.4.3, body-parser@1.13.3, serve-index@1.7.3)
├── jstransform@11.0.3 (object-assign@2.1.1, base62@1.1.1, esprima-fb@15001.1.0-dev-harmony-fb, commoner@0.10.4)
├── module-deps@3.9.1 (browser-resolve@1.11.2, through2@1.1.1, inherits@2.0.1, defined@1.0.0, duplexer2@0.0.2, xtend@4.0.1, concat-stream@1.4.10, parents@1.0.1, readable-stream@1.1.14, subarg@1.0.0, JSONStream@1.1.2, stream-combiner2@1.0.2, resolve@1.1.7, detective@4.3.1)
├── babel-plugin-external-helpers@6.8.0 (babel-runtime@6.9.2)
├── babel-polyfill@6.9.1 (babel-runtime@6.9.2)
├── babylon@6.8.1 (babel-runtime@6.9.2)
├── joi@6.10.1 (topo@1.1.0, isemail@1.2.0, hoek@2.16.3, moment@2.13.0)
├── lodash@3.10.1
├── babel-register@6.9.0 (path-exists@1.0.0, home-or-tmp@1.0.0, source-map-support@0.2.10, babel-runtime@6.9.2, lodash@4.13.1)
├── yeoman-environment@1.6.1 (escape-string-regexp@1.0.5, log-symbols@1.0.2, text-table@0.2.0, untildify@2.1.0, diff@2.2.3, globby@4.1.0, mem-fs@1.1.3, grouped-queue@0.3.2, inquirer@1.0.3, lodash@4.13.1)
├── babel-types@6.10.2 (to-fast-properties@1.0.2, esutils@2.0.2, babel-traverse@6.9.0, babel-runtime@6.9.2, lodash@4.13.1)
├── babel-core@6.9.1 (slash@1.0.0, babel-messages@6.8.0, shebang-regex@1.0.0, babel-template@6.9.0, path-exists@1.0.0, path-is-absolute@1.0.0, babel-helpers@6.8.0, private@0.1.6, convert-source-map@1.2.0, babel-code-frame@6.8.0, source-map@0.5.6, minimatch@2.0.10, babel-traverse@6.9.0, babel-generator@6.10.2, babel-runtime@6.9.2, lodash@4.13.1)
├── react-transform-hmr@1.0.4 (global@4.3.0, react-proxy@1.1.8)
├── yeoman-generator@0.20.3 (read-chunk@1.0.1, detect-conflict@1.0.0, path-exists@1.0.0, yeoman-welcome@1.0.1, path-is-absolute@1.0.0, async@1.5.2, mime@1.3.4, text-table@0.2.0, class-extend@0.1.2, user-home@2.0.0, xdg-basedir@2.0.0, dargs@4.1.0, istextorbinary@1.0.2, nopt@3.0.6, diff@2.2.3, shelljs@0.5.3, run-async@0.1.0, yeoman-assert@2.2.1, cli-table@0.3.1, glob@5.0.15, through2@2.0.1, findup-sync@0.2.1, rimraf@2.5.2, mem-fs-editor@2.2.1, underscore.string@3.3.4, cross-spawn@2.2.3, sinon@1.17.4, pretty-bytes@2.0.1, github-username@2.1.0, dateformat@1.0.12, download@4.4.3, html-wiring@1.2.0, inquirer@0.8.5, gruntfile-editor@1.2.0)
├── fbjs@0.8.3 (object-assign@4.1.0, ua-parser-js@0.7.10, loose-envify@1.2.0, isomorphic-fetch@2.2.1, core-js@1.2.6)
├── babel-preset-react-native@1.9.0 (babel-plugin-transform-react-display-name@6.8.0, babel-plugin-transform-es2015-literals@6.8.0, babel-plugin-transform-flow-strip-types@6.8.0, babel-plugin-transform-es2015-shorthand-properties@6.8.0, babel-plugin-syntax-async-functions@6.8.0, babel-plugin-syntax-jsx@6.8.0, babel-plugin-syntax-class-properties@6.8.0, babel-plugin-check-es2015-constants@6.8.0, babel-plugin-transform-react-jsx-source@6.9.0, babel-plugin-transform-es2015-arrow-functions@6.8.0, babel-plugin-transform-es2015-template-literals@6.8.0, babel-plugin-transform-es2015-destructuring@6.9.0, babel-plugin-transform-es2015-spread@6.8.0, babel-plugin-transform-class-properties@6.10.2, babel-plugin-syntax-flow@6.8.0, babel-plugin-transform-es2015-for-of@6.8.0, babel-plugin-transform-object-assign@6.8.0, babel-plugin-transform-object-rest-spread@6.8.0, babel-plugin-syntax-trailing-function-commas@6.8.0, babel-plugin-transform-es2015-block-scoping@6.10.1, babel-plugin-transform-es2015-modules-commonjs@6.10.3, babel-plugin-transform-es2015-computed-properties@6.8.0, babel-plugin-transform-react-jsx@6.8.0, babel-plugin-transform-es2015-classes@6.9.0, babel-plugin-transform-es2015-parameters@6.9.0, babel-plugin-transform-es2015-function-name@6.9.0, babel-plugin-transform-regenerator@6.9.0, babel-plugin-react-transform@2.0.2)
├── core-js@2.4.0
└── fbjs-scripts@0.4.0 (object-assign@4.1.0, through2@2.0.1, gulp-util@3.0.7, core-js@1.2.6, babel@5.8.38)

**Comment by jondot** [comment]
Looks good. Did you try a clean rebuild in Xcode? try also reopening the project (see here https://github.com/oblador/react-native-vector-icons/issues/2)

**Comment by tahirwaseer** [comment]
Thankyou @jondot it worked!

**Comment by jondot** [comment]
Yes!! Enjoy!
