### ISSUE TITLE
Add / Modify Labels for Certain Katas

### ISSUE THREAD

**Issue by conroywhitney** [jondot/ReactNativeKatas#5]
Very cool project. Thanks for putting this together!

Most of the katas have a `<Text>` label with the name of the kata which is a great idea. These labels are very helpful for knowing which file corresponds with the given kata. However, there are a few katas which currently do not have indicative labels:
- [FlexSize](https://github.com/jondot/ReactNativeKatas/blob/master/src/katas/flex/FlexSize.js)
- [BorderRadius](https://github.com/jondot/ReactNativeKatas/blob/master/src/katas/styling/BorderRadius.js)
- [Clipping](https://github.com/jondot/ReactNativeKatas/blob/master/src/katas/styling/Clipping.js)
- [ContactCard](https://github.com/jondot/ReactNativeKatas/blob/master/src/katas/composing/ContactCard.js)
- [ProfileScreen](https://github.com/jondot/ReactNativeKatas/blob/master/src/katas/composing/ProfileScreen.js)
- [CalendarMonth](https://github.com/jondot/ReactNativeKatas/blob/master/src/katas/composing/CalendarMonth.js)

Also, the  [SimpleChart.test.js](https://github.com/jondot/ReactNativeKatas/blob/master/src/katas/composing/SimpleChart.test.js) kata's label reads as `Chart!` instead of `SimpleChart!`

Even without labels, it's still possible to determine which file to edit by either looking at the [list of katas on the README](https://github.com/jondot/ReactNativeKatas#katas) or at [the ordered list of katas in `bundle.js`](https://github.com/jondot/ReactNativeKatas/blob/master/src/katas/bundle.js). The addition of labels would just make it that much easier.

What would you think of adding / modifying the labels for the above katas?

**Comment by jondot** [comment]
Hello! Thanks! I'm happy you find the Katas useful!
You're observing right. I went back and forth on this writing and rewriting the code just to address this supposedly minuscule issue of having a label that represents the current Kata.
When I started the more complex Katas it was clear that having a label right the obstructed the design and I guess this is exactly the thing you notice to be less harmonious.
Eventually I could not make up my mind so I figured I'll let people trying this influence a direction :)
So I'm open to any suggestions and pull requests - your idea sounds fine!

**Comment by conroywhitney** [comment]
You're right -- adding `<Text />` components in the middle of those Katas makes everything more difficult! I see why you left them off in the more complex Katas.

Instead, what do you think about PR #6 which adds a navbar to the top of the runner?

This not only gets us the name of the current Kata, but in the future, could also allow us to do things like adding `< Back` and `Next >` buttons to cycle through all of the various Katas. 

Let me know what you think and if you want me to change anything.

**Comment by jondot** [comment]
@conroywhitney your PR was fantastic, I've merged it in, updated katas to remove the label and refreshed the screenshot, kudos!

**Comment by conroywhitney** [comment]
Awesome  👍  

Good call on f2fceb31168462aaaaababf22d3043865c3e599c for removing the text from the katas which no longer need them. You could probably also get rid of the `text: {}` styles in those examples too if you want.

Let me know if you'd like me to submit a PR for adding `Next >` and `< Back` buttons, or if there's anything else I can do to help with this project.

Thanks again for all your work!

**Comment by jondot** [comment]
Hey Conroy,
Yes I don't see why not, a next/back would be awesome to have. I made sure Runner is ready for such things by externalizing the index here: https://github.com/jondot/ReactNativeKatas/blob/master/src/katas/index.js

So the way to go about it might be to consider fiddling with `index` or building it into runner itself like in [here](https://github.com/jondot/ReactNativeKatas/blob/master/src/runner/index.js#L34).

A thing to remember is, that if you step back and that Kata is done, it'll be advanced automatically. But - maybe automatically advancing can be disabled once you fiddle with next/back :)

I'm very interested to see how you solve it if you decide this might be fun to do so feel free to pull me in if you have questions about how to do it. I'd be happy to remove any obstacles for you!

**Comment by jondot** [comment]
Thanks!!!
Cleaning up resolved issues 👍
