### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by mharper418** [jondot/ReactNativeKatas#8]
Is this project iOS only?  When run in Android, there is an error "UIManager.takeSnapshot is not available on this platform".

**Comment by jondot** [comment]
Hi, please see the discussion here: https://github.com/jondot/ReactNativeKatas/issues/7

**Comment by sugang1990** [comment]
run 的时候报错，\MainActivity.java:27: 错误: 方法不会覆盖或实现超类型的方法             
    @Override                                  
求解释

**Comment by jondot** [comment]
Now assigned to #20
